=== bellmit/MSFM/client/release/dtd/CommandCallback.dtd
<!-- This provides configuration information for the CommandCallbackHomeImpl -->
<!-- @author Dave Hoag -->
<!-- @version 1.0 -->
<!ENTITY % reusableElements SYSTEM "Header.dtd" >
%reusableElements;

<!ELEMENT GlobalCommandCallbackService (CommandCallbackService* )>
<!ATTLIST GlobalCommandCallbackService  type		  %typeConstraints;  #FIXED 'ManagedResource'
	objectName  CDATA	 #IMPLIED >

<!ELEMENT CommandCallbackService (CommandCallbackServiceProperties ) >
<!ATTLIST CommandCallbackService  type		  %typeConstraints;  #FIXED 'ManagedResource'
			name		ID	 #REQUIRED
			objectName  CDATA	 #IMPLIED
			container   CDATA #FIXED 'frameworkContainer' >

<!ELEMENT CommandCallbackServiceProperties  ( HTTPPort? )>
<!ATTLIST CommandCallbackServiceProperties  type  %typeConstraints;  #FIXED 'ManagedProperties' >


<!ELEMENT HTTPPort (#PCDATA)>
<!ATTLIST HTTPPort type	%typeConstraints;  #FIXED 'ManagedProperty'
	mode		  %modeConstraints;  #FIXED 'readWrite'
	propertyType  %propertyTypes;  #FIXED 'string'
	description CDATA #FIXED 'The port number to use to listen for HTTP requests. ' >

=== bellmit/MSFM/FoundationFramework/release/xml/CommandCallback.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.0b3 NT (http://www.xmlspy.com) by Dave (OW) -->
<!DOCTYPE GlobalCommandCallbackService SYSTEM "../dtd/CommandCallback.dtd">
<GlobalCommandCallbackService>
	<CommandCallbackService name="DefaultService">
		<CommandCallbackServiceProperties>
			<HTTPPort>3003</HTTPPort>
		</CommandCallbackServiceProperties>
	</CommandCallbackService>
	<CommandCallbackService name="CAS">
		<CommandCallbackServiceProperties>
			<HTTPPort>4004</HTTPPort>
		</CommandCallbackServiceProperties>
	</CommandCallbackService>
	<CommandCallbackService name="ACAS">
		<CommandCallbackServiceProperties>
			<HTTPPort>5005</HTTPPort>
		</CommandCallbackServiceProperties>
	</CommandCallbackService>
	<CommandCallbackService name="SystemPropertyDefined">
		<CommandCallbackServiceProperties>
			<HTTPPort>&lt;prefixCommandHttpPort&gt;</HTTPPort>
		</CommandCallbackServiceProperties>
	</CommandCallbackService>
</GlobalCommandCallbackService>
