=== bellmit/MSFM/client/release/dtd/UserQuoteServiceHome.dtd
<!-- edited with XML Spy v3.0 NT (http://www.xmlspy.com) by William Wei (CBOE) -->
<!-- This provides configuration information for the UserQuoteServiceHomeImpl -->
<!-- @author William Wei, Troy Wehrle-->
<!-- @version 2.0 -->
<!ENTITY % reusableElements SYSTEM "Header.dtd">
%reusableElements;
<!ELEMENT GlobalUserQuoteServiceHome (UserQuoteServiceHomeImpl*)>
<!ATTLIST GlobalUserQuoteServiceHome
	type %typeConstraints; #FIXED "ManagedResource"
	objectName CDATA #IMPLIED
>
<!ELEMENT UserQuoteServiceHomeImpl (UserQuoteServiceHomeImplProperties, UserQuoteServiceHomeImplCommands?)>
<!ATTLIST UserQuoteServiceHomeImpl
	type %typeConstraints; #FIXED "ManagedResource"
	name ID #REQUIRED
	objectName CDATA #IMPLIED
	container CDATA #FIXED "frameworkContainer"
>
<!ELEMENT UserQuoteServiceHomeImplProperties (quoteDeleteReportDispatch?, rateMonitorSessions?, rateMonitorStartTime?, rateMonitorInterval?, rateMonitorWindow?, quoteRateMonitorInterval?, quoteRateMonitorWindow?, rateMonitorQuoteSequenceSize?)>
<!ATTLIST UserQuoteServiceHomeImplProperties
	type %typeConstraints; #FIXED "ManagedProperties"
>
<!ELEMENT quoteDeleteReportDispatch (#PCDATA)>
<!ATTLIST quoteDeleteReportDispatch
	type %typeConstraints; #FIXED "ManagedProperty"
	mode %modeConstraints; #FIXED "readWrite"
	propertyType %propertyTypes; #FIXED "enum"
	booleanValue (true | false) #REQUIRED
	propertyValue CDATA #FIXED "booleanValue"
>
<!ELEMENT rateMonitorSessions (#PCDATA)>
<!ATTLIST rateMonitorSessions
	type %typeConstraints; #FIXED "ManagedProperty"
	mode %modeConstraints; #FIXED "readWrite"
	propertyType %propertyTypes; #FIXED "string"
	description CDATA #FIXED "Identifies the sessions to set rate monitor constraints for and the order that the constraints must follow. If a constraint is not desired for a particular session, set it to zero. Delimit individual sessions with a comma."
>
<!ELEMENT rateMonitorStartTime (#PCDATA)>
<!ATTLIST rateMonitorStartTime
	type %typeConstraints; #FIXED "ManagedProperty"
	mode %modeConstraints; #FIXED "readWrite"
	propertyType %propertyTypes; #FIXED "string"
	description CDATA #FIXED "Time of day when rateMonitor goes into effect. Specify start time as h:mm, or 0 to mean always in effect. Delimit individual sessions with a comma."
>
<!ELEMENT rateMonitorInterval (#PCDATA)>
<!ATTLIST rateMonitorInterval
	type %typeConstraints; #FIXED "ManagedProperty"
	mode %modeConstraints; #FIXED "readWrite"
	propertyType %propertyTypes; #FIXED "string"
	description CDATA #FIXED "Defines the time duration call window constraints for sessions. The order of constraints for session must follow the same order as the sessions are defined. Delimit individual constraints with a comma."
>
<!ELEMENT rateMonitorWindow (#PCDATA)>
<!ATTLIST rateMonitorWindow
	type %typeConstraints; #FIXED "ManagedProperty"
	mode %modeConstraints; #FIXED "readWrite"
	propertyType %propertyTypes; #FIXED "string"
	description CDATA #FIXED "Defines the frequency count call window constraints for sessions. The order of constraints for session must follow the same order as the sessions are defined. Delimit individual constraints with a comma."
>
<!ELEMENT quoteRateMonitorInterval (#PCDATA)>
<!ATTLIST quoteRateMonitorInterval
	type %typeConstraints; #FIXED "ManagedProperty"
	mode %modeConstraints; #FIXED "readWrite"
	propertyType %propertyTypes; #FIXED "string"
	description CDATA #FIXED "Defines the time duration quote count constraints for sessions. The order of constraints for session must follow the same order as the sessions are defined. Delimit individual constraints with a comma."
>
<!ELEMENT quoteRateMonitorWindow (#PCDATA)>
<!ATTLIST quoteRateMonitorWindow
	type %typeConstraints; #FIXED "ManagedProperty"
	mode %modeConstraints; #FIXED "readWrite"
	propertyType %propertyTypes; #FIXED "string"
	description CDATA #FIXED "Defines the quote count constraints for sessions. The order of constraints for session must follow the same order as the sessions are defined. Delimit individual constraints with a comma."
>
<!ELEMENT rateMonitorQuoteSequenceSize (#PCDATA)>
<!ATTLIST rateMonitorQuoteSequenceSize
	type %typeConstraints; #FIXED "ManagedProperty"
	mode %modeConstraints; #FIXED "readWrite"
	propertyType %propertyTypes; #FIXED "string"
	description CDATA #FIXED "Defines the quote sequence size constraints for sessions. The sequence size constraints are for all calls that accept a sequence. The order of constraints for session must follow the same order as the sessions are defined. Delimit individual constraints with a comma."
>
<!ELEMENT UserQuoteServiceHomeImplCommands (quoteRateMonitor)>
<!ATTLIST UserQuoteServiceHomeImplCommands
        type %typeConstraints; #FIXED "ManagedCommands"
>
<!ELEMENT quoteRateMonitor (command, pattern?)>
<!ATTLIST quoteRateMonitor
	type %typeConstraints; #FIXED "ManagedCommand"
	description CDATA #FIXED "Display Quote RateMoniotr"
>
<!ELEMENT command (#PCDATA)>
<!ATTLIST command
	type %typeConstraints; #FIXED "ManagedCommand"
	parameterType CDATA #FIXED "string"
	description CDATA #FIXED "ALL"
>
<!ELEMENT pattern (#PCDATA)>
<!ATTLIST pattern
	type %typeConstraints; #FIXED "ManagedCommand"
	parameterType CDATA #FIXED "string"
	description CDATA #FIXED "ALL"
>

=== bellmit/MSFM/client/release/xml/UserQuoteServiceHome.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v3.0 NT (http://www.xmlspy.com) by Chicago Board Options Exchange (Chicago Board Options Exchange) -->
<!DOCTYPE GlobalUserQuoteServiceHome SYSTEM "../dtd/UserQuoteServiceHome.dtd">
<GlobalUserQuoteServiceHome>
	<UserQuoteServiceHomeImpl name="DefaultService">
		<UserQuoteServiceHomeImplProperties>
			<quoteDeleteReportDispatch booleanValue="true"/>
			<rateMonitorSessions>CFE_MAIN,W_MAIN,ONE_MAIN,W_STOCK,C2_MAIN,COF_MAIN</rateMonitorSessions>
			<rateMonitorStartTime>8:15,8:25,8:15,7:45,9:15,8:25</rateMonitorStartTime>
			<rateMonitorInterval>5000,1000,5000,1000,1000,1000</rateMonitorInterval>
			<!-- OVERRIDE cas01v2devcas5  REPLACE <rateMonitorWindow>250,10000,250,200,10000</rateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas1 REPLACE <rateMonitorWindow>250,10000,250,200,10000</rateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas2 REPLACE <rateMonitorWindow>250,10000,250,200,10000</rateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas3 REPLACE <rateMonitorWindow>250,10000,250,200,10000</rateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas4 REPLACE <rateMonitorWindow>250,10000,250,200,10000</rateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas5 REPLACE <rateMonitorWindow>250,10000,250,200,10000</rateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas6 REPLACE <rateMonitorWindow>250,10000,250,200,10000</rateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas9 REPLACE <rateMonitorWindow>250,10000,250,200,10000</rateMonitorWindow> -->
			<!-- OVERRIDE cas01v2sbtcas3  REPLACE <rateMonitorWindow>250,10000,250,200,10000</rateMonitorWindow> -->
			<!-- OVERRIDE cas01v2sbtcas4  REPLACE <rateMonitorWindow>250,10000,250,200,10000</rateMonitorWindow> -->
			<!-- OVERRIDE cas01v2sbtcas5  REPLACE <rateMonitorWindow>250,10000,250,200,10000</rateMonitorWindow> -->
			<rateMonitorWindow>250,133,250,133,200,133</rateMonitorWindow>
			<!-- OVERRIDE cas01v2devcas5  REPLACE <quoteRateMonitorInterval>5000,1000,5000,0,1000</quoteRateMonitorInterval> -->
			<!-- OVERRIDE cas01v2perfcas1 REPLACE <quoteRateMonitorInterval>5000,1000,5000,0,1000</quoteRateMonitorInterval> -->
			<!-- OVERRIDE cas01v2perfcas2 REPLACE <quoteRateMonitorInterval>5000,1000,5000,0,1000</quoteRateMonitorInterval> -->
			<!-- OVERRIDE cas01v2perfcas3 REPLACE <quoteRateMonitorInterval>5000,1000,5000,0,1000</quoteRateMonitorInterval> -->
			<!-- OVERRIDE cas01v2perfcas4 REPLACE <quoteRateMonitorInterval>5000,1000,5000,0,1000</quoteRateMonitorInterval> -->
			<!-- OVERRIDE cas01v2perfcas5 REPLACE <quoteRateMonitorInterval>5000,1000,5000,0,1000</quoteRateMonitorInterval> -->
			<!-- OVERRIDE cas01v2perfcas6 REPLACE <quoteRateMonitorInterval>5000,1000,5000,0,1000</quoteRateMonitorInterval> -->
			<!-- OVERRIDE cas01v2perfcas9 REPLACE <quoteRateMonitorInterval>5000,1000,5000,0,1000</quoteRateMonitorInterval> -->
			<!-- OVERRIDE cas01v2sbtcas3  REPLACE <quoteRateMonitorInterval>5000,1000,5000,0,1000</quoteRateMonitorInterval> -->
			<!-- OVERRIDE cas01v2sbtcas4  REPLACE <quoteRateMonitorInterval>5000,1000,5000,0,1000</quoteRateMonitorInterval> -->
			<!-- OVERRIDE cas01v2sbtcas5  REPLACE <quoteRateMonitorInterval>5000,1000,5000,0,1000</quoteRateMonitorInterval> -->
			<quoteRateMonitorInterval>5000,3000,5000,3000,3000,3000</quoteRateMonitorInterval>
			<!-- OVERRIDE cas01v2devcas5  REPLACE <quoteRateMonitorWindow>1000,20000,1000,0,20000</quoteRateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas1 REPLACE <quoteRateMonitorWindow>1000,20000,1000,0,20000</quoteRateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas2 REPLACE <quoteRateMonitorWindow>1000,20000,1000,0,20000</quoteRateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas3 REPLACE <quoteRateMonitorWindow>1000,20000,1000,0,20000</quoteRateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas4 REPLACE <quoteRateMonitorWindow>1000,20000,1000,0,20000</quoteRateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas5 REPLACE <quoteRateMonitorWindow>1000,20000,1000,0,20000</quoteRateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas6 REPLACE <quoteRateMonitorWindow>1000,20000,1000,0,20000</quoteRateMonitorWindow> -->
			<!-- OVERRIDE cas01v2perfcas9 REPLACE <quoteRateMonitorWindow>1000,20000,1000,0,20000</quoteRateMonitorWindow> -->
			<!-- OVERRIDE cas01v2sbtcas3  REPLACE <quoteRateMonitorWindow>1000,20000,1000,0,20000</quoteRateMonitorWindow> -->
			<!-- OVERRIDE cas01v2sbtcas4  REPLACE <quoteRateMonitorWindow>1000,20000,1000,0,20000</quoteRateMonitorWindow> -->
			<!-- OVERRIDE cas01v2sbtcas5  REPLACE <quoteRateMonitorWindow>1000,20000,1000,0,20000</quoteRateMonitorWindow> -->
			<quoteRateMonitorWindow>1000,4000,1000,4000,4000,4000</quoteRateMonitorWindow>
			<rateMonitorQuoteSequenceSize>12,400,12,400,400,400</rateMonitorQuoteSequenceSize>
		</UserQuoteServiceHomeImplProperties>
	</UserQuoteServiceHomeImpl>
</GlobalUserQuoteServiceHome>
