=== bellmit/MSFM/client/release/dtd/UserSessionMarketDataThreadPoolHome.dtd
<!-- edited with XML Spy v3.0 NT (http://www.xmlspy.com) by William Wei (CBOE) -->
<!-- This provides configuration information for the UserSessionMarketDataThreadPoolHomeImpl -->
<!-- @author William Wei-->
<!-- @version 1.0 -->
<!ENTITY % reusableElements SYSTEM "Header.dtd">
%reusableElements;
<!ELEMENT GlobalUserSessionMarketDataThreadPoolHome (UserSessionMarketDataThreadPoolHomeImpl*)>
<!ATTLIST GlobalUserSessionMarketDataThreadPoolHome
	type %typeConstraints; #FIXED "ManagedResource"
	objectName CDATA #IMPLIED
>
<!ELEMENT UserSessionMarketDataThreadPoolHomeImpl (UserSessionMarketDataThreadPoolHomeImplProperties)>
<!ATTLIST UserSessionMarketDataThreadPoolHomeImpl
	type %typeConstraints; #FIXED "ManagedResource"
	name ID #REQUIRED
	objectName CDATA #IMPLIED
	container CDATA #FIXED "frameworkContainer"
>
<!ELEMENT UserSessionMarketDataThreadPoolHomeImplProperties (UserSessionMarketDataThreadPoolSize?, UserSessionMarketDataOverlayThreadPoolSize? , UserRoleOverride?, ThreadPoolSizeOverride?, OverlayThreadPoolSizeOverride? )>
<!ATTLIST UserSessionMarketDataThreadPoolHomeImplProperties
	type %typeConstraints; #FIXED "ManagedProperties"
>
<!ELEMENT UserSessionMarketDataThreadPoolSize (#PCDATA)>
<!ATTLIST UserSessionMarketDataThreadPoolSize
	type %typeConstraints; #FIXED "ManagedProperty"
	mode %modeConstraints; #FIXED "readWrite"
	propertyType %propertyTypes; #FIXED "integer"
	description CDATA #FIXED "user session thread pool size"
>
<!ELEMENT UserSessionMarketDataOverlayThreadPoolSize (#PCDATA)>
<!ATTLIST UserSessionMarketDataOverlayThreadPoolSize
	type %typeConstraints; #FIXED "ManagedProperty"
	mode %modeConstraints; #FIXED "readWrite"
	propertyType %propertyTypes; #FIXED "integer"
	description CDATA #FIXED "Each user session share a thread pool to deliver overlay market data, this attribute defins the size of that thread pool"
>
<!ELEMENT UserRoleOverride (#PCDATA)>
<!ATTLIST UserRoleOverride
	type %typeConstraints; #FIXED "ManagedProperty"
	mode %modeConstraints; #FIXED "readWrite"
	propertyType %propertyTypes; #FIXED "string"
	description CDATA #FIXED "user role override"
>
<!ELEMENT ThreadPoolSizeOverride (#PCDATA)>
<!ATTLIST ThreadPoolSizeOverride
	type %typeConstraints; #FIXED "ManagedProperty"
	mode %modeConstraints; #FIXED "readWrite"
	propertyType %propertyTypes; #FIXED "string"
	description CDATA #FIXED "thread pool size override"
>
<!ELEMENT OverlayThreadPoolSizeOverride (#PCDATA)>
<!ATTLIST OverlayThreadPoolSizeOverride
	type %typeConstraints; #FIXED "ManagedProperty"
	mode %modeConstraints; #FIXED "readWrite"
	propertyType %propertyTypes; #FIXED "string"
	description CDATA #FIXED "overlay thread pool size override"
>

=== bellmit/MSFM/client/release/xml/UserSessionMarketDataThreadPoolHome.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.0 NT (http://www.xmlspy.com) by Chicago Board Options Exchange (Chicago Board Options Exchange) -->
<!DOCTYPE GlobalUserSessionMarketDataThreadPoolHome SYSTEM "../dtd/UserSessionMarketDataThreadPoolHome.dtd">
<GlobalUserSessionMarketDataThreadPoolHome>
	<UserSessionMarketDataThreadPoolHomeImpl name="DefaultService">
		<UserSessionMarketDataThreadPoolHomeImplProperties>
			<UserSessionMarketDataThreadPoolSize>4</UserSessionMarketDataThreadPoolSize>
			<UserSessionMarketDataOverlayThreadPoolSize>4</UserSessionMarketDataOverlayThreadPoolSize>
			<UserRoleOverride>C</UserRoleOverride>
			<ThreadPoolSizeOverride>4</ThreadPoolSizeOverride>
			<OverlayThreadPoolSizeOverride>4</OverlayThreadPoolSizeOverride>
		</UserSessionMarketDataThreadPoolHomeImplProperties>
	</UserSessionMarketDataThreadPoolHomeImpl>
</GlobalUserSessionMarketDataThreadPoolHome>
